'use client';
import {useEffect,useRef} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {useCommerce} from './commerce-provider';
import {formatPrice} from '@/lib/catalog';
export function CartDrawer(){
 const {cartOpen,closeCart,cart,cartCount,ready,busy,message,updateQuantity,removeFromCart}=useCommerce();const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const dialog=ref.current;if(!dialog)return;if(cartOpen){dialog.showModal();const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{dialog.close();document.body.style.overflow=previous;};}dialog.close();},[cartOpen]);
 const subtotal=cart.reduce((sum,line)=>sum+(line.product.salePrice??line.product.price)*line.quantity,0);
 return <dialog ref={ref} className="cart-drawer" aria-labelledby="cart-drawer-title" onCancel={closeCart} onClick={e=>{if(e.target===e.currentTarget){const rect=e.currentTarget.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right)closeCart();}}}><div className="drawer-header"><h2 id="cart-drawer-title">Your cart <span>({cartCount})</span></h2><button className="icon-button" onClick={closeCart} aria-label="Close cart">×</button></div><div className="drawer-items">{!ready?<p role="status">Loading your cart…</p>:!cart.length?<div className="empty-state"><h3>Your cart is empty</h3><p>Find a frame you like and add it here.</p><Link href="/shop" className="button button-dark" onClick={closeCart}>Browse eyewear</Link></div>:cart.map(line=><article className="drawer-item" key={line.variantId}><Link href={'/products/'+line.product.slug} onClick={closeCart} className="drawer-photo">{line.product.images[0]&&<Image src={line.product.images[0].url} alt={line.product.name} fill sizes="96px"/>}</Link><div><Link href={'/products/'+line.product.slug} onClick={closeCart}><h3>{line.product.name}</h3></Link><p>{line.product.color}</p><strong>{formatPrice((line.product.salePrice??line.product.price)*line.quantity)}</strong><div className="drawer-item-actions"><div className="quantity-stepper"><button disabled={busy||line.quantity<=1} aria-label={'Decrease '+line.product.name+' quantity'} onClick={()=>void updateQuantity(line.variantId,line.quantity-1).catch(()=>{})}>−</button><output aria-label={line.product.name+' quantity'}>{line.quantity}</output><button disabled={busy||line.quantity>=Math.min(50,line.product.stock)} aria-label={'Increase '+line.product.name+' quantity'} onClick={()=>void updateQuantity(line.variantId,line.quantity+1).catch(()=>{})}>+</button></div><button className="link-button" disabled={busy} onClick={()=>void removeFromCart(line.variantId).catch(()=>{})}>Remove</button></div>{(!line.available||line.quantity>line.product.stock)&&<p className="danger">Please update or remove this item before checkout.</p>}</div></article>)}</div>{message&&<p role="status" className="drawer-message">{message}</p>}{cart.length>0&&<div className="drawer-footer"><div><span>Subtotal</span><strong>{formatPrice(subtotal)}</strong></div><p>Delivery and discounts are calculated at checkout.</p><Link href="/checkout" onClick={closeCart} className="button button-dark button-wide">Checkout <span>→</span></Link><Link href="/cart" onClick={closeCart} className="drawer-view-cart">View full cart</Link></div>}</dialog>;
}
