'use client';
import { useEffect,useState } from 'react';
import { useRouter } from 'next/navigation';
import { ProductCard } from './product-card';
import { EmptyState } from './ui';
import type { Facets,PageResult,Product } from '@/lib/catalog';

export function CatalogBrowser({result,facets,query}:{result:PageResult<Product>;facets:Facets;query:Record<string,string>}){
  const router=useRouter();const [search,setSearch]=useState(query.q??'');
  useEffect(()=>{setSearch(query.q??'');},[query.q]);
  useEffect(()=>{const timer=setTimeout(()=>{if(search!==(query.q??'')){const params=new URLSearchParams(query);search?params.set('q',search):params.delete('q');params.delete('page');router.push(`/shop?${params}`);}},350);return()=>clearTimeout(timer);},[search,query,router]);
  function filter(key:string,value:string){const params=new URLSearchParams(query);value?params.set(key,value):params.delete(key);if(key!=='page')params.delete('page');router.push(`/shop?${params}`);}
  const selectors=[{key:'category',label:'Category',values:facets.categories.map(c=>c.name)},{key:'brand',label:'Brand',values:facets.brands.map(b=>b.name)},{key:'gender',label:'For',values:facets.genders},{key:'shape',label:'Shape',values:facets.shapes},{key:'material',label:'Material',values:facets.materials},{key:'color',label:'Colour',values:facets.colors},{key:'lens',label:'Lens',values:facets.lenses}];
  return <div className="catalog-layout"><aside className="filters" aria-label="Product filters"><div className="filter-heading"><h2>Refine your search</h2><button className="link-button" onClick={()=>{setSearch('');router.push('/shop');}}>Reset</button></div>{selectors.map(s=><label key={s.key}>{s.label}<select value={query[s.key]??''} onChange={e=>filter(s.key,e.target.value)}><option value="">All {s.label.toLowerCase()}</option>{s.values.map(value=><option key={value}>{value}</option>)}</select></label>)}<div className="form-row"><label>Min price<input type="number" min="0" defaultValue={query.min} onBlur={e=>filter('min',e.target.value)} /></label><label>Max price<input type="number" min="0" defaultValue={query.max} onBlur={e=>filter('max',e.target.value)} /></label></div><label className="checkbox-label"><input type="checkbox" checked={query.availability==='in-stock'} onChange={e=>filter('availability',e.target.checked?'in-stock':'')} />In stock only</label></aside><div><div className="catalog-toolbar"><label className="search-box"><span className="sr-only">Search frames, brands or SKU</span><input type="search" placeholder="Search frames, brands or SKU" value={search} onChange={e=>setSearch(e.target.value)} /></label><label className="sort-select"><span className="sr-only">Sort products</span><select value={query.sort??'newest'} onChange={e=>filter('sort',e.target.value)}><option value="newest">Newest first</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option><option value="popular">Popular</option><option value="best-selling">Best selling</option></select></label></div><p className="result-count">{result.total} products</p>{result.items.length?<div className="product-grid catalog-grid">{result.items.map(product=><ProductCard key={product.id} product={product}/>)}</div>:<EmptyState title="No frames match your search">Try a different shape, brand, or price range.</EmptyState>}<div className="pagination" aria-label="Catalog pages"><button className="button button-outline" disabled={result.page<=1} onClick={()=>filter('page',String(result.page-1))}>Previous</button><span>Page {result.page} of {Math.max(1,result.pages??1)}</span><button className="button button-outline" disabled={result.page>=(result.pages??1)} onClick={()=>filter('page',String(result.page+1))}>Next</button></div></div></div>;
}
