'use client';
import Image from 'next/image';
import {useEffect,useRef,useState} from 'react';
export function ProductImageViewer({photo}:{photo:{url:string;alt:string}}){
 const [open,setOpen]=useState(false),[zoom,setZoom]=useState(1);const dialog=useRef<HTMLDialogElement>(null);const area=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!open)return;const el=dialog.current!;const previous=document.body.style.overflow;el.showModal();document.body.style.overflow='hidden';return()=>{el.close();document.body.style.overflow=previous;};},[open]);
 function changeZoom(value:number){setZoom(Math.max(1,Math.min(3,value)));}
 return <><button className="gallery-zoom-trigger" aria-label={'Open detailed view of '+photo.alt} onClick={()=>{setZoom(1);setOpen(true);}} onPointerMove={e=>{if(e.pointerType!=='mouse')return;const rect=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--zoom-x',`${Math.max(0,Math.min(100,(e.clientX-rect.left)/rect.width*100))}%`);e.currentTarget.style.setProperty('--zoom-y',`${Math.max(0,Math.min(100,(e.clientY-rect.top)/rect.height*100))}%`);}}><Image src={photo.url} alt={photo.alt} fill sizes="(max-width:900px) 100vw, 55vw" priority className="object-cover"/><span className="gallery-zoom-lens" aria-hidden="true"/><span className="gallery-zoom-hint"><span className="desktop-zoom-copy">Hover to inspect · </span>Click to enlarge</span></button><dialog ref={dialog} className="product-image-dialog" aria-label="Product image viewer" onCancel={()=>setOpen(false)}><div className="image-viewer-toolbar"><span>Inspect frame details</span><div><button aria-label="Zoom out" disabled={zoom<=1} onClick={()=>changeZoom(zoom-.5)}>−</button><output aria-live="polite">{Math.round(zoom*100)}%</output><button aria-label="Zoom in" disabled={zoom>=3} onClick={()=>changeZoom(zoom+.5)}>＋</button><button onClick={()=>setZoom(1)}>Reset</button><button aria-label="Close image viewer" onClick={()=>setOpen(false)}>×</button></div></div><div className="image-viewer-area" ref={area} onPointerMove={e=>{if(zoom<=1||e.pointerType!=='mouse')return;const el=e.currentTarget,r=el.getBoundingClientRect();el.scrollLeft=(e.clientX-r.left)/r.width*(el.scrollWidth-el.clientWidth);el.scrollTop=(e.clientY-r.top)/r.height*(el.scrollHeight-el.clientHeight);}}><div className="image-viewer-canvas" style={{width:`${zoom*100}%`,height:`${zoom*100}%`}}><Image src={photo.url} alt={photo.alt} fill sizes="100vw" unoptimized style={{objectFit:'contain'}}/></div></div><p className="image-viewer-help">Use + / − to zoom. Move your pointer or scroll to inspect details. Press Escape to close.</p></dialog></>;
}
