'use client';
import Link from 'next/link';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {useCommerce} from './commerce-provider';
export function SiteHeader(){
 const {cartCount,user,openCart}=useCommerce();const [open,setOpen]=useState(false);const router=useRouter();
 return <header className="site-header"><Link href="/" className="brand" aria-label="Bonoful Optics home"><span className="brand-mark">bo</span><span>Bonoful <em>Optics</em></span></Link><nav aria-label="Primary navigation" className={open?'nav-open':''}>{[['Shop','/shop'],['Eyeglasses','/shop?category=Eyeglasses'],['Sunglasses','/shop?category=Sunglasses']].map(([label,href])=><Link key={label} href={href} onClick={()=>setOpen(false)}>{label}</Link>)}</nav><div className="header-actions"><form className="header-search" onSubmit={e=>{e.preventDefault();const q=new FormData(e.currentTarget).get('q');router.push('/shop?q='+encodeURIComponent(String(q??'')));}}><label className="sr-only" htmlFor="header-search">Search products</label><input id="header-search" name="q" type="search" placeholder="Search frames…"/><button aria-label="Search" type="submit"><svg viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg></button></form><Link className="account-link" href={user?'/account':'/login'} aria-label={user?'My account':'Sign in'}><svg viewBox="0 0 24 24" width="23" height="23" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><circle cx="12" cy="8" r="4"/><path d="M4 22v-3a8 8 0 0 1 16 0v3"/></svg><span>{user?'Account':'Sign in'}</span></Link><button className="bag" onClick={openCart} aria-label={'Open cart, '+cartCount+' items'}><svg viewBox="0 0 24 24" width="23" height="23" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="M5 8h14l1 13H4L5 8Z"/><path d="M8 8V6a4 4 0 0 1 8 0v2"/></svg><span>{cartCount}</span></button><button className="menu-button" aria-expanded={open} aria-label="Toggle menu" onClick={()=>setOpen(v=>!v)}>{open?'Close':'Menu'}</button></div></header>;
}
