import { BadRequestException, Body, Controller, Delete, Get, Param, Patch, Post, Query, Req } from '@nestjs/common';
import { ApiTags } from '@nestjs/swagger';
import { OrderStatus } from '@prisma/client';
import { z } from 'zod';
import { AuthRequest, Require } from '../core/auth.guard';
import { PrismaService } from '../core/prisma.service';
import { InventoryService } from '../inventory/inventory.service';
import { OrderService, orderInclude, orderView } from '../commerce/order.service';
import { hashPassword } from '../auth/auth.service';
import { ProductAdminService } from './product-admin.service';
import { PurchasingService } from './purchasing.service';
import { AdminQueryService, listQuery } from './admin-query.service';

@ApiTags('Administration') @Controller('admin')
export class AdminController {
  constructor(private readonly db:PrismaService,private readonly queries:AdminQueryService,private readonly products:ProductAdminService,private readonly inventory:InventoryService,private readonly purchasing:PurchasingService,private readonly orders:OrderService) {}
  @Require('reports.read') @Get() dashboard() {return this.queries.dashboard();}
  @Require('products.read') @Get('products') listProducts(@Query() query:Record<string,string>){return this.queries.products(query);}
  @Require('products.read') @Get('products/:id') product(@Param('id') id:string){return this.db.product.findUniqueOrThrow({where:{id},include:{variants:{include:{inventory:true}},images:true}});}
  @Require('products.create') @Post('products') createProduct(@Body() body:unknown,@Req() req:AuthRequest){return this.products.save(body,req.actor!.id);}
  @Require('products.update') @Patch('products/:id') updateProduct(@Param('id') id:string,@Body() body:unknown,@Req() req:AuthRequest){return this.products.save(body,req.actor!.id,id);}
  @Require('products.delete') @Delete('products/:id') archive(@Param('id') id:string,@Req() req:AuthRequest){return this.products.archive(id,req.actor!.id);}
  @Require('products.update') @Post('products/bulk') bulk(@Body() body:unknown,@Req() req:AuthRequest){return this.products.bulk(body,req.actor!.id);}
  @Require('products.update') @Post('categories') category(@Body() body:unknown,@Req() req:AuthRequest){return this.taxonomy('category',body,req.actor!.id);}
  @Require('products.update') @Post('brands') brand(@Body() body:unknown,@Req() req:AuthRequest){return this.taxonomy('brand',body,req.actor!.id);}
  private async taxonomy(kind:'category'|'brand',body:unknown,actorId:string) {const data=z.object({id:z.string().optional(),name:z.string().trim().min(2).max(60),slug:z.string().regex(/^[a-z0-9-]+$/)}).strict().parse(body);return this.db.atomic(async(tx)=>{const {id,...values}=data;const result=kind==='brand'?(id?await tx.brand.update({where:{id},data:values}):await tx.brand.create({data:values})):(id?await tx.category.update({where:{id},data:values}):await tx.category.create({data:values}));await tx.auditLog.create({data:{actorId,action:`${kind}.save`,entity:kind,entityId:result.id}});return result;});}
  @Require('inventory.read') @Get('inventory') stock(@Query() query:Record<string,string>){return this.queries.inventory(query);}
  @Require('inventory.read') @Get('movements') movements(@Query() query:Record<string,string>){return this.queries.movements(query);}
  @Require('inventory.adjust') @Post('inventory/adjust') adjust(@Body() body:unknown,@Req() req:AuthRequest){return this.inventory.adjust(body,req.actor!.id);}
  @Require('inventory.adjust') @Patch('inventory/:id') async threshold(@Param('id') id:string,@Body() body:unknown,@Req() req:AuthRequest){const data=z.object({lowThreshold:z.number().int().min(0).max(10000)}).strict().parse(body);return this.db.atomic(async(tx)=>{const row=await tx.inventory.update({where:{id},data});await tx.auditLog.create({data:{actorId:req.actor!.id,action:'inventory.threshold',entity:'inventory',entityId:id,detail:data}});return row;});}
  @Require('orders.read') @Get('orders') listOrders(@Query() query:Record<string,string>){return this.queries.orders(query);}
  @Require('orders.read') @Get('orders/:id') async order(@Param('id') id:string){const order=await this.db.order.findUniqueOrThrow({where:{id},include:orderInclude});return {...orderView(order),internalNote:order.internalNote};}
  @Require('orders.update') @Post('orders/:id/status') status(@Param('id') id:string,@Body() body:unknown,@Req() req:AuthRequest){const {status,...data}=z.object({status:z.nativeEnum(OrderStatus),note:z.string().max(500).optional(),trackingNumber:z.string().max(100).optional(),restock:z.boolean().optional()}).strict().parse(body);if(status==='REFUNDED'&&!req.actor!.role.permissions.some(p=>p.permissionId==='orders.refund'))throw new BadRequestException('Refund permission is required.');return this.orders.transition(id,status,req.actor!.id,data);}
  @Require('orders.update') @Patch('orders/:id/notes') async notes(@Param('id') id:string,@Body() body:unknown,@Req() req:AuthRequest){const data=z.object({internalNote:z.string().max(2000)}).strict().parse(body);return this.db.atomic(async(tx)=>{await tx.order.update({where:{id},data});await tx.auditLog.create({data:{actorId:req.actor!.id,action:'orders.notes',entity:'order',entityId:id}});return {message:'Note saved.'};});}
  @Require('orders.refund') @Post('refunds/:id/settle') async settle(@Param('id') id:string,@Req() req:AuthRequest){return this.db.atomic(async(tx)=>{const refund=await tx.refund.findUniqueOrThrow({where:{id},include:{payment:true}});if(refund.status!=='REQUESTED'||refund.payment.provider!=='COD')throw new BadRequestException('Only a pending cash refund can be settled manually.');await tx.refund.update({where:{id},data:{status:'COMPLETED'}});await tx.payment.update({where:{id:refund.paymentId},data:{status:'REFUNDED'}});await tx.auditLog.create({data:{actorId:req.actor!.id,action:'refunds.settle',entity:'refund',entityId:id}});return {message:'Cash refund recorded.'};});}
  @Require('purchases.read') @Get('suppliers') async suppliers(@Query() query:Record<string,string>){const {page,q}=listQuery.parse(query);const where={name:{contains:q,mode:'insensitive' as const}};const [items,total]=await Promise.all([this.db.supplier.findMany({where,take:20,skip:(page-1)*20,include:{_count:{select:{purchases:true}}}}),this.db.supplier.count({where})]);return {items,total,page};}
  @Require('purchases.manage') @Post('suppliers') async supplier(@Body() body:unknown,@Req() req:AuthRequest){const {id,...data}=z.object({id:z.string().optional(),name:z.string().min(2).max(100),email:z.email(),phone:z.string().min(7).max(25),address:z.string().min(3).max(300),active:z.boolean().default(true)}).strict().parse(body);return this.db.atomic(async(tx)=>{const result=id?await tx.supplier.update({where:{id},data}):await tx.supplier.create({data});await tx.auditLog.create({data:{actorId:req.actor!.id,action:'suppliers.save',entity:'supplier',entityId:result.id}});return result;});}
  @Require('purchases.read') @Get('purchase-orders') async purchases(@Query() query:Record<string,string>){const {page,q}=listQuery.parse(query);const where={number:{contains:q,mode:'insensitive' as const}};const [items,total]=await Promise.all([this.db.purchaseOrder.findMany({where,include:{supplier:true,items:{include:{variant:{select:{sku:true,product:{select:{name:true}}}}}}},orderBy:{createdAt:'desc'},take:20,skip:(page-1)*20}),this.db.purchaseOrder.count({where})]);return {items,total,page};}
  @Require('purchases.manage') @Post('purchase-orders') purchase(@Body() body:unknown,@Req() req:AuthRequest){return this.purchasing.create(body,req.actor!.id);}
  @Require('purchases.manage') @Post('purchase-orders/:id/receive') receive(@Param('id') id:string,@Body() body:unknown,@Req() req:AuthRequest){return this.purchasing.receive(id,body,req.actor!.id);}
  @Require('purchases.manage') @Post('purchase-orders/:id/status') purchaseStatus(@Param('id') id:string,@Body() body:unknown,@Req() req:AuthRequest){const data=z.object({status:z.enum(['ORDERED','CANCELLED'])}).strict().parse(body);return this.purchasing.status(id,data.status,req.actor!.id);}
  @Require('customers.read') @Get('customers') async customers(@Query() query:Record<string,string>){const {page,q}=listQuery.parse(query);const where={roleId:'customer',OR:[{email:{contains:q,mode:'insensitive' as const}},{name:{contains:q,mode:'insensitive' as const}}]};const [items,total]=await Promise.all([this.db.user.findMany({where,select:{id:true,name:true,email:true,phone:true,active:true,verifiedAt:true,createdAt:true,_count:{select:{orders:true}}},take:20,skip:(page-1)*20}),this.db.user.count({where})]);return {items,total,page};}
  @Require('customers.read') @Get('customers/:id') customer(@Param('id') id:string){return this.db.user.findFirstOrThrow({where:{id,roleId:'customer'},select:{id:true,name:true,email:true,phone:true,active:true,orders:{select:{id:true,number:true,status:true,total:true,createdAt:true},take:50,orderBy:{createdAt:'desc'}}}});}
  @Require('customers.manage') @Patch('customers/:id') async customerStatus(@Param('id') id:string,@Body() body:unknown,@Req() req:AuthRequest){const data=z.object({active:z.boolean()}).strict().parse(body);return this.db.atomic(async(tx)=>{await tx.user.update({where:{id,roleId:'customer'},data});if(!data.active)await tx.session.deleteMany({where:{userId:id}});await tx.auditLog.create({data:{actorId:req.actor!.id,action:'customers.status',entity:'user',entityId:id,detail:data}});return {message:'Customer updated.'};});}
  @Require('users.manage') @Get('staff') async staff(){return {items:await this.db.user.findMany({where:{roleId:{not:'customer'}},select:{id:true,name:true,email:true,active:true,roleId:true,role:true}})};}
  @Require('users.manage') @Get('roles') roles(){return this.db.role.findMany({include:{permissions:true}});}
  @Require('users.manage') @Get('permissions') permissions(){return this.db.permission.findMany();}
  @Require('users.manage') @Post('staff') async saveStaff(@Body() body:unknown,@Req() req:AuthRequest){const data=z.object({id:z.string().optional(),name:z.string().min(2).max(100),email:z.email(),roleId:z.string(),active:z.boolean().default(true),password:z.string().min(12).max(128).regex(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).+$/).optional()}).strict().parse(body);if(data.id===req.actor!.id)throw new BadRequestException('You cannot change your own role or status.');if(!data.id&&!data.password)throw new BadRequestException('Initial password is required.');const passwordHash=data.password?await hashPassword(data.password):undefined;return this.db.atomic(async(tx)=>{const role=await tx.role.findUniqueOrThrow({where:{id:data.roleId}});if(role.id==='customer')throw new BadRequestException('Use customer management for customer accounts.');const values={name:data.name,email:data.email.toLowerCase(),roleId:data.roleId,active:data.active,...(passwordHash?{passwordHash}:{})};const user=data.id?await tx.user.update({where:{id:data.id,roleId:{not:'customer'}},data:values}):await tx.user.create({data:{...values,passwordHash:passwordHash!,verifiedAt:new Date()}});await tx.session.deleteMany({where:{userId:user.id}});await tx.auditLog.create({data:{actorId:req.actor!.id,action:'users.manage',entity:'user',entityId:user.id,detail:{roleId:user.roleId,active:user.active}}});return {id:user.id};});}
  @Require('users.manage') @Post('roles') async role(@Body() body:unknown,@Req() req:AuthRequest){const {id,name,permissions}=z.object({id:z.string().regex(/^[a-z_-]+$/),name:z.string().min(2).max(60),permissions:z.array(z.string()).max(50)}).strict().parse(body);if(['super_admin','customer'].includes(id))throw new BadRequestException('This built-in role cannot be changed.');return this.db.atomic(async(tx)=>{await tx.role.upsert({where:{id},create:{id,name},update:{name}});await tx.rolePermission.deleteMany({where:{roleId:id}});await tx.rolePermission.createMany({data:[...new Set(permissions)].map(permissionId=>({roleId:id,permissionId}))});await tx.auditLog.create({data:{actorId:req.actor!.id,action:'roles.update',entity:'role',entityId:id,detail:{permissions}}});return {id};});}
  @Require('promotions.manage') @Get('coupons') async coupons(){return {items:await this.db.coupon.findMany({include:{_count:{select:{usages:true}},products:true,categories:true},orderBy:{createdAt:'desc'},take:100})};}
  @Require('promotions.manage') @Post('coupons') async coupon(@Body() body:unknown,@Req() req:AuthRequest){const {id,productIds,categoryIds,...data}=z.object({id:z.string().optional(),code:z.string().min(3).max(40).transform(v=>v.toUpperCase()),type:z.enum(['PERCENT','FIXED']),value:z.number().int().min(1),minimum:z.number().int().min(0).default(0),startsAt:z.iso.datetime(),endsAt:z.iso.datetime(),usageLimit:z.number().int().min(1),perCustomerLimit:z.number().int().min(1),active:z.boolean(),productIds:z.array(z.string()).max(100).default([]),categoryIds:z.array(z.string()).max(100).default([])}).strict().refine(d=>d.type!=='PERCENT'||d.value<=100,'Percent must be at most 100.').refine(d=>new Date(d.endsAt)>new Date(d.startsAt),'End must follow start.').parse(body);return this.db.atomic(async(tx)=>{const coupon=id?await tx.coupon.update({where:{id},data}):await tx.coupon.create({data});await tx.couponProduct.deleteMany({where:{couponId:coupon.id}});await tx.couponCategory.deleteMany({where:{couponId:coupon.id}});if(productIds.length)await tx.couponProduct.createMany({data:[...new Set(productIds)].map(productId=>({couponId:coupon.id,productId}))});if(categoryIds.length)await tx.couponCategory.createMany({data:[...new Set(categoryIds)].map(categoryId=>({couponId:coupon.id,categoryId}))});await tx.auditLog.create({data:{actorId:req.actor!.id,action:'coupons.save',entity:'coupon',entityId:coupon.id}});return coupon;});}
  @Require('reviews.moderate') @Get('reviews') async reviews(@Query() query:Record<string,string>){const {page}=listQuery.parse(query);return {items:await this.db.review.findMany({include:{user:{select:{name:true}},product:{select:{name:true}}},orderBy:{createdAt:'desc'},skip:(page-1)*20,take:20}),total:await this.db.review.count(),page};}
  @Require('reviews.moderate') @Patch('reviews/:id') async moderate(@Param('id') id:string,@Body() body:unknown,@Req() req:AuthRequest){const data=z.object({approved:z.boolean()}).strict().parse(body);return this.db.atomic(async(tx)=>{const review=await tx.review.update({where:{id},data});await tx.auditLog.create({data:{actorId:req.actor!.id,action:'reviews.moderate',entity:'review',entityId:id,detail:data}});return review;});}
  @Require('audit.read') @Get('audit') audit(@Query() query:Record<string,string>){return this.queries.audit(query);}
  @Require('orders.read') @Get('appointments') async appointments(){return {items:await this.db.appointment.findMany({take:100,orderBy:{preferredAt:'asc'}})};}
  @Require('orders.update') @Patch('appointments/:id') appointment(@Param('id') id:string,@Body() body:unknown){const data=z.object({status:z.enum(['CONFIRMED','COMPLETED','CANCELLED'])}).strict().parse(body);return this.db.appointment.update({where:{id},data});}
}
