'use client';
import {useEffect,useState} from 'react';
import {api,errorMessage,send} from '@/lib/api';
import {Dialog} from './dialog';
import {Alert} from '../ui';
export type Row=Record<string,unknown>;
export const str=(value:unknown)=>value==null?'':String(value);
export const obj=(value:unknown)=>value&&typeof value==='object'?value as Row:{};
export const arr=(value:unknown)=>Array.isArray(value)?value as Row[]:[];
type Field={key:string;label:string;type?:string;options?:string[];default?:string|number;optional?:boolean};
const forms:Record<string,Field[]>={suppliers:[{key:'name',label:'Supplier name'},{key:'email',label:'Email',type:'email'},{key:'phone',label:'Phone'},{key:'address',label:'Address'}],categories:[{key:'name',label:'Category name'},{key:'slug',label:'URL slug'}],brands:[{key:'name',label:'Brand name'},{key:'slug',label:'URL slug'}],coupons:[{key:'code',label:'Code'},{key:'type',label:'Discount type',options:['PERCENT','FIXED']},{key:'value',label:'Value (% or paisa)',type:'number',default:10},{key:'minimum',label:'Minimum order (paisa)',type:'number',default:0},{key:'startsAt',label:'Starts',type:'datetime-local'},{key:'endsAt',label:'Ends',type:'datetime-local'},{key:'usageLimit',label:'Total usage limit',type:'number',default:100},{key:'perCustomerLimit',label:'Per-customer limit',type:'number',default:1}],staff:[{key:'name',label:'Full name'},{key:'email',label:'Email',type:'email'},{key:'password',label:'Initial or new password',type:'password',optional:true}]};
function dateInput(value:unknown){if(!value)return '';const date=new Date(str(value));return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);}
export function ResourceEditor({kind,row,onClose,onSaved}:{kind:string;row?:Row;onClose:()=>void;onSaved:()=>void}){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[roles,setRoles]=useState<Row[]>([]),[facets,setFacets]=useState<{categories:Row[];brands:Row[]}|null>(null),[productIds,setProducts]=useState(arr(row?.products).map(r=>str(r.productId))),[categoryIds,setCategories]=useState(arr(row?.categories).map(r=>str(r.categoryId)));
 useEffect(()=>{if(kind==='staff')void api<Row[]>('admin/roles').then(setRoles).catch(e=>setError(errorMessage(e)));if(kind==='coupons')void api<{categories:Row[];brands:Row[]}>('catalog/facets').then(setFacets).catch(e=>setError(errorMessage(e)));},[kind]);
 return <Dialog title={`${row?'Edit':'New'} ${kind.replaceAll('-',' ')}`} onClose={onClose}><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);const payload:Row={};if(row?.id)payload.id=row.id;for(const field of forms[kind]??[]){const value=form.get(field.key);if(field.optional&&!value)continue;payload[field.key]=field.type==='number'?Number(value):field.type==='datetime-local'?new Date(str(value)).toISOString():value;}
 if(['suppliers','staff','coupons'].includes(kind))payload.active=form.get('active')==='on';if(kind==='staff')payload.roleId=form.get('roleId');if(kind==='coupons'){payload.productIds=productIds;payload.categoryIds=categoryIds;}
 try{await send(`admin/${kind}`,payload);onSaved();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}}><div className="form-grid">{(forms[kind]??[]).map(field=><label key={field.key}>{field.label}{field.options?<select name={field.key} defaultValue={str(row?.[field.key]??field.default??field.options[0])}>{field.options.map(option=><option key={option}>{option}</option>)}</select>:<input name={field.key} type={field.type??'text'} defaultValue={field.type==='datetime-local'?dateInput(row?.[field.key]??(field.key==='startsAt'?new Date().toISOString():new Date(Date.now()+30*86400000).toISOString())):str(row?.[field.key]??field.default)} required={!field.optional||kind==='staff'&&!row&&field.key==='password'} min={field.type==='number'?0:undefined} minLength={field.type==='password'?12:undefined}/>}</label>)}{kind==='staff'&&<label>Role<select name="roleId" defaultValue={str(row?.roleId??'staff')}>{roles.filter(r=>r.id!=='customer').map(role=><option key={str(role.id)} value={str(role.id)}>{str(role.name)}</option>)}</select></label>}{['suppliers','staff','coupons'].includes(kind)&&<label className="checkbox-label"><input type="checkbox" name="active" defaultChecked={row?Boolean(row.active):true}/>Active</label>}</div>{kind==='coupons'&&<><fieldset><legend>Restrict to categories (optional)</legend>{facets?.categories.map(c=><label className="checkbox-label" key={str(c.id)}><input type="checkbox" checked={categoryIds.includes(str(c.id))} onChange={e=>setCategories(ids=>e.target.checked?[...ids,str(c.id)]:ids.filter(id=>id!==c.id))}/>{str(c.name)}</label>)}</fieldset><label>Product IDs (optional, comma-separated)<input value={productIds.join(',')} onChange={e=>setProducts(e.target.value.split(',').map(v=>v.trim()).filter(Boolean))}/><small>Leave both restrictions empty to apply to all products.</small></label></>}{error&&<Alert>{error}</Alert>}<div className="dialog-actions"><button type="button" className="button button-outline" onClick={onClose}>Cancel</button><button className="button button-dark" disabled={busy}>{busy?'Saving…':'Save'}</button></div></form></Dialog>;
}
export function RoleEditor({row,onClose,onSaved}:{row?:Row;onClose:()=>void;onSaved:()=>void}){const [permissions,setPermissions]=useState<Row[]>([]),[selected,setSelected]=useState(arr(row?.permissions).map(p=>str(p.permissionId))),[error,setError]=useState('');useEffect(()=>{void api<Row[]>('admin/permissions').then(setPermissions).catch(e=>setError(errorMessage(e)));},[]);return <Dialog title="Role permissions" onClose={onClose}><form onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);try{await send('admin/roles',{id:form.get('id'),name:form.get('name'),permissions:selected});onSaved();}catch(e){setError(errorMessage(e));}}}><div className="form-grid"><label>Role key<input name="id" pattern="[a-z_-]+" defaultValue={str(row?.id)} readOnly={!!row} required/></label><label>Role name<input name="name" defaultValue={str(row?.name)} required/></label></div><fieldset><legend>Allowed actions</legend><div className="permissions-grid">{permissions.map(permission=><label key={str(permission.id)} className="checkbox-label"><input type="checkbox" checked={selected.includes(str(permission.id))} onChange={e=>setSelected(ids=>e.target.checked?[...ids,str(permission.id)]:ids.filter(id=>id!==permission.id))}/>{str(permission.id)}</label>)}</div></fieldset>{error&&<Alert>{error}</Alert>}<button className="button button-dark">Save role</button></form></Dialog>;}
