import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { serverApi,getProducts } from '@/lib/server-api';
import type { Product } from '@/lib/catalog';
import { ProductDetail } from '@/components/product-detail';
import { ProductCard } from '@/components/product-card';
import { Breadcrumb } from '@/components/ui';
export const dynamic='force-dynamic';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;try{const product=await serverApi<Product>(`products/${encodeURIComponent(slug)}`);return {title:product.name,description:product.description,alternates:{canonical:`/products/${product.slug}`},openGraph:{title:product.name,description:product.description,images:product.images.map(i=>({url:i.url,alt:i.alt}))},twitter:{title:product.name,description:product.description,images:product.images.map(i=>i.url)}};}catch{return {title:'Product unavailable',robots:{index:false}};}}
export default async function ProductPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;let product:Product;try{product=await serverApi<Product>(`products/${encodeURIComponent(slug)}`);}catch{notFound();}const matches=await Promise.allSettled([getProducts(`category=${encodeURIComponent(product.category)}&limit=12`),getProducts(`shape=${encodeURIComponent(product.shape)}&limit=12`),getProducts(`brand=${encodeURIComponent(product.brand)}&limit=12`)]);const candidates=[...new Map(matches.flatMap(r=>r.status==='fulfilled'?r.value.items:[]).filter(p=>p.id!==product.id).map(p=>[p.id,p])).values()];const score=(p:Product)=>(p.category===product.category?8:0)+(p.shape===product.shape?4:0)+(p.brand===product.brand?3:0)+(p.material===product.material?2:0)+(p.gender===product.gender?1:0);const related=candidates.sort((a,b)=>score(b)-score(a)||Math.abs(a.price-product.price)-Math.abs(b.price-product.price)).slice(0,4);const origin=process.env.NEXT_PUBLIC_SITE_URL??'http://localhost:3000';const structured={'@context':'https://schema.org','@type':'Product',name:product.name,description:product.description,sku:product.sku,image:product.images.map(i=>new URL(i.url,origin).href),brand:{'@type':'Brand',name:product.brand},offers:{'@type':'Offer',priceCurrency:'BDT',price:product.salePrice??product.price,availability:product.stock?'https://schema.org/InStock':'https://schema.org/OutOfStock',url:new URL(`/products/${product.slug}`,origin).href}};return <main className="page-shell"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structured).replace(/</g,'\u003c')}}/><Breadcrumb items={[{label:'The collection',href:'/shop'},{label:product.name}]}/><ProductDetail product={product}/>{related.length>0&&<section className="related-section"><div className="section-heading"><h2>You might also like</h2></div><div className="product-grid">{related.map(p=><ProductCard key={p.id} product={p}/>)}</div></section>}</main>;}
